In [452]:
import pandas as pd
import pandas_ta as ta
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LassoCV
df = pd.read_csv("Nairobi Office Price Ex.csv")
df=pd.read_csv('modified_data.csv')
df.tail()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  \
1455  1456          60       RL         62.0     7917   Pave      Reg   
1456  1457          20       RL         85.0    13175   Pave      Reg   
1457  1458          70       RL         66.0     9042   Pave      Reg   
1458  1459          20       RL         68.0     9717   Pave      Reg   
1459  1460          20       RL         75.0     9937   Pave      Reg   

     LandContour Utilities LotConfig  ... EnclosedPorch 3SsnPorch ScreenPorch  \
1455         Lvl    AllPub    Inside  ...             0         0           0   
1456         Lvl    AllPub    Inside  ...             0         0           0   
1457         Lvl    AllPub    Inside  ...             0         0           0   
1458         Lvl    AllPub    Inside  ...           112         0           0   
1459         Lvl    AllPub    Inside  ...             0         0           0   

     PoolArea MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
1455        0       0      8    2007        WD         Normal     175000  
1456        0       0      2    2010        WD         Normal     210000  
1457        0    2500      5    2010        WD         Normal     266500  
1458        0       0      4    2010        WD         Normal     142125  
1459        0       0      6    2008        WD         Normal     147500  

[5 rows x 77 columns]

In [453]:
df.shape

(1460, 77)

In [454]:
indexZeros = df[ df['SalePrice'] == 0 ].index

df.drop(indexZeros , inplace=True)
df.loc[(df["SalePrice"] == 0 )]
df.isna().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 77, dtype: int64

In [455]:
import pandas as pd
df = pd.read_csv("modified_data.csv")
df.head(5)


Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0   1          60       RL         65.0     8450   Pave      Reg         Lvl   
1   2          20       RL         80.0     9600   Pave      Reg         Lvl   
2   3          60       RL         68.0    11250   Pave      IR1         Lvl   
3   4          70       RL         60.0     9550   Pave      IR1         Lvl   
4   5          60       RL         84.0    14260   Pave      IR1         Lvl   

  Utilities LotConfig  ... EnclosedPorch 3SsnPorch ScreenPorch PoolArea  \
0    AllPub    Inside  ...             0         0           0        0   
1    AllPub       FR2  ...             0         0           0        0   
2    AllPub    Inside  ...             0         0           0        0   
3    AllPub    Corner  ...           272         0           0        0   
4    AllPub       FR2  ...             0         0           0        0   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0       0      2    2008        WD         Normal     208500  
1       0      5    2007        WD         Normal     181500  
2       0      9    2008        WD         Normal     223500  
3       0      2    2006        WD        Abnorml     140000  
4       0     12    2008        WD         Normal     250000  

[5 rows x 77 columns]

In [456]:
df.shape

(1460, 77)

In [457]:
indexZeros = df[ df['SalePrice'] == 0 ].index

df.drop(indexZeros , inplace=True)
df.loc[(df["SalePrice"] == 0 )]
df.isna().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 77, dtype: int64

In [458]:
df.drop('Id',inplace=True,axis=1)

In [459]:
df.tail(3)

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
1457          70       RL         66.0     9042   Pave      Reg         Lvl   
1458          20       RL         68.0     9717   Pave      Reg         Lvl   
1459          20       RL         75.0     9937   Pave      Reg         Lvl   

     Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
1457    AllPub    Inside       Gtl  ...             0         0           0   
1458    AllPub    Inside       Gtl  ...           112         0           0   
1459    AllPub    Inside       Gtl  ...             0         0           0   

     PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
1457        0    2500       5    2010        WD         Normal    266500  
1458        0       0       4    2010        WD         Normal    142125  
1459        0       0       6    2008        WD         Normal    147500  

[3 rows x 76 columns]

In [460]:
original_features=list(df.columns)
len(original_features)

76

In [461]:
features_missing_values=list(df.columns[df.isna().any()])
len(features_missing_values)

15

In [462]:
len(df)

1460

# Filling In Missing Features

In [463]:
bfill,mean_fill=[],[]

In [464]:
for feature in features_missing_values:
  print(feature,' ',df[feature].isna().sum()/len(df)*100,' ',df[feature].dtype)
  if df[feature].dtype=='float64':
    mean_fill.append(feature)
  else:
    bfill.append(feature)

LotFrontage   17.73972602739726   float64
MasVnrType   0.547945205479452   object
MasVnrArea   0.547945205479452   float64
BsmtQual   2.5342465753424657   object
BsmtCond   2.5342465753424657   object
BsmtExposure   2.6027397260273974   object
BsmtFinType1   2.5342465753424657   object
BsmtFinType2   2.6027397260273974   object
Electrical   0.0684931506849315   object
FireplaceQu   47.26027397260274   object
GarageType   5.5479452054794525   object
GarageYrBlt   5.5479452054794525   float64
GarageFinish   5.5479452054794525   object
GarageQual   5.5479452054794525   object
GarageCond   5.5479452054794525   object


In [465]:
mean_fill

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [466]:
for feature in mean_fill:
  df[feature].fillna(df[feature].mean(),inplace=True)

In [467]:
for feature in bfill:
  df[feature].fillna(method='bfill',inplace=True)

In [468]:
df.columns[df.isna().any()]

Index(['FireplaceQu'], dtype='object')

In [469]:
df['FireplaceQu'].isna().sum()

2

In [470]:
df['FireplaceQu'].fillna(method='ffill',inplace=True)

## ENCODE THE DATASET

In [471]:
categorical_features=list(df.select_dtypes(include=['object']).columns)
categorical_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [472]:
numerical=list(set(original_features)-set(categorical_features))
numerical

['LotArea',
 'GarageCars',
 'YearBuilt',
 'BsmtUnfSF',
 'PoolArea',
 'OverallQual',
 '3SsnPorch',
 'MSSubClass',
 'TotRmsAbvGrd',
 'Fireplaces',
 'TotalBsmtSF',
 'BedroomAbvGr',
 'MasVnrArea',
 'BsmtFullBath',
 'OverallCond',
 'EnclosedPorch',
 'FullBath',
 'MoSold',
 'BsmtHalfBath',
 'SalePrice',
 'OpenPorchSF',
 'LotFrontage',
 'GarageArea',
 'BsmtFinSF2',
 'KitchenAbvGr',
 'WoodDeckSF',
 'GarageYrBlt',
 'YrSold',
 'BsmtFinSF1',
 '2ndFlrSF',
 'MiscVal',
 '1stFlrSF',
 'YearRemodAdd',
 'LowQualFinSF',
 'GrLivArea',
 'ScreenPorch',
 'HalfBath']

In [473]:
categorical_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [474]:
nominal=['MSZoning','LandContour','Neighborhood']
ordinal=list(set(categorical_features)-set(nominal))

In [475]:
target=['SalePrice']

In [476]:
df_nominal=pd.get_dummies(df[nominal])

In [477]:
for feature in ordinal:
  df[feature]=df[feature].astype('category').cat.codes

df_ordinal=df[ordinal]

In [478]:
df[numerical]

LotArea  GarageCars  YearBuilt  BsmtUnfSF  PoolArea  OverallQual  \
0        8450           2       2003        150         0            7   
1        9600           2       1976        284         0            6   
2       11250           2       2001        434         0            7   
3        9550           3       1915        540         0            7   
4       14260           3       2000        490         0            8   
...       ...         ...        ...        ...       ...          ...   
1455     7917           2       1999        953         0            6   
1456    13175           2       1978        589         0            6   
1457     9042           1       1941        877         0            7   
1458     9717           1       1950          0         0            5   
1459     9937           1       1965        136         0            5   

      3SsnPorch  MSSubClass  TotRmsAbvGrd  Fireplaces  ...  YrSold  \
0             0          60             8           0  ...    2008   
1             0          20             6           1  ...    2007   
2             0          60             6           1  ...    2008   
3             0          70             7           1  ...    2006   
4             0          60             9           1  ...    2008   
...         ...         ...           ...         ...  ...     ...   
1455          0          60             7           1  ...    2007   
1456          0          20             7           2  ...    2010   
1457          0          70             9           2  ...    2010   
1458          0          20             5           0  ...    2010   
1459          0          20             6           0  ...    2008   

      BsmtFinSF1  2ndFlrSF  MiscVal  1stFlrSF  YearRemodAdd  LowQualFinSF  \
0            706       854        0       856          2003             0   
1            978         0        0      1262          1976             0   
2            486       866        0       920          2002             0   
3            216       756        0       961          1970             0   
4            655      1053        0      1145          2000             0   
...          ...       ...      ...       ...           ...           ...   
1455           0       694        0       953          2000             0   
1456         790         0        0      2073          1988             0   
1457         275      1152     2500      1188          2006             0   
1458          49         0        0      1078          1996             0   
1459         830         0        0      1256          1965             0   

      GrLivArea  ScreenPorch  HalfBath  
0          1710            0         1  
1          1262            0         0  
2          1786            0         1  
3          1717            0         0  
4          2198            0         1  
...         ...          ...       ...  
1455       1647            0         1  
1456       2073            0         0  
1457       2340            0         0  
1458       1078            0         0  
1459       1256            0         1  

[1460 rows x 37 columns]

In [479]:
nominal=['MSZoning','LandContour','Neighborhood']
ordinal=list(set(categorical_features)-set(nominal))

In [480]:
target=['SalePrice']

In [481]:
df_nominal=pd.get_dummies(df[nominal])

In [482]:
for feature in ordinal:
  df[feature]=df[feature].astype('category').cat.codes

df_ordinal=df[ordinal]

In [483]:
df[numerical]

LotArea  GarageCars  YearBuilt  BsmtUnfSF  PoolArea  OverallQual  \
0        8450           2       2003        150         0            7   
1        9600           2       1976        284         0            6   
2       11250           2       2001        434         0            7   
3        9550           3       1915        540         0            7   
4       14260           3       2000        490         0            8   
...       ...         ...        ...        ...       ...          ...   
1455     7917           2       1999        953         0            6   
1456    13175           2       1978        589         0            6   
1457     9042           1       1941        877         0            7   
1458     9717           1       1950          0         0            5   
1459     9937           1       1965        136         0            5   

      3SsnPorch  MSSubClass  TotRmsAbvGrd  Fireplaces  ...  YrSold  \
0             0          60             8           0  ...    2008   
1             0          20             6           1  ...    2007   
2             0          60             6           1  ...    2008   
3             0          70             7           1  ...    2006   
4             0          60             9           1  ...    2008   
...         ...         ...           ...         ...  ...     ...   
1455          0          60             7           1  ...    2007   
1456          0          20             7           2  ...    2010   
1457          0          70             9           2  ...    2010   
1458          0          20             5           0  ...    2010   
1459          0          20             6           0  ...    2008   

      BsmtFinSF1  2ndFlrSF  MiscVal  1stFlrSF  YearRemodAdd  LowQualFinSF  \
0            706       854        0       856          2003             0   
1            978         0        0      1262          1976             0   
2            486       866        0       920          2002             0   
3            216       756        0       961          1970             0   
4            655      1053        0      1145          2000             0   
...          ...       ...      ...       ...           ...           ...   
1455           0       694        0       953          2000             0   
1456         790         0        0      2073          1988             0   
1457         275      1152     2500      1188          2006             0   
1458          49         0        0      1078          1996             0   
1459         830         0        0      1256          1965             0   

      GrLivArea  ScreenPorch  HalfBath  
0          1710            0         1  
1          1262            0         0  
2          1786            0         1  
3          1717            0         0  
4          2198            0         1  
...         ...          ...       ...  
1455       1647            0         1  
1456       2073            0         0  
1457       2340            0         0  
1458       1078            0         0  
1459       1256            0         1  

[1460 rows x 37 columns]

In [484]:
new_df=pd.concat([df_nominal,df_ordinal,df[numerical]],axis=1)

In [485]:
new_df.shape

(1460, 107)

In [486]:
new_df.drop('SalePrice',axis=1,inplace=True)

In [487]:
X=new_df.to_numpy()

In [488]:
X[0]

array([0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 4.000e+00, 0.000e+00,
       2.000e+00, 1.000e+00, 1.000e+00, 2.000e+00, 1.000e+00, 2.000e+00,
       4.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 2.000e+00, 4.000e+00,
       2.000e+00, 2.000e+00, 6.000e+00, 3.000e+00, 4.000e+00, 1.000e+00,
       4.000e+00, 4.000e+00, 0.000e+00, 1.200e+01, 8.000e+00, 1.000e+00,
       4.000e+00, 3.000e+00, 2.000e+00, 1.000e+00, 5.000e+00, 1.300e+01,
       2.000e+00, 3.000e+00, 5.000e+00, 0.000e+00, 8.450e+03, 2.000e+00,
       2.003e+03, 1.500e+02, 0.000e+00, 7.000e+00, 0.000e+00, 6.000e+01,
       8.000e+00, 0.000e+00, 8.560e+02, 3.000e+00, 

In [489]:
X=StandardScaler().fit_transform(X)

In [490]:
X[0]

array([-0.08304548, -0.21585871, -0.10526316,  0.51813339, -0.41895507,
       -0.21235968, -0.18831089, -0.15899968,  0.33712564, -0.10854037,
       -0.03703704, -0.10526316, -0.20339487, -0.1398323 ,  2.95522137,
       -0.19025216, -0.27116307, -0.23917551, -0.16124951, -0.10854037,
       -0.1863522 , -0.42683279, -0.07875671, -0.22941573, -0.16998114,
       -0.23595776, -0.28963792, -0.13199092, -0.23106504, -0.20521398,
       -0.25018188, -0.13199092, -0.16347148, -0.08712888,  0.18797343,
       -0.02618016, -0.29055229,  0.06423821, -0.49151573, -0.40936914,
       -0.23012211, -0.40779461,  0.22403433, -0.41169079, -0.12304604,
       -0.12579688,  0.83559903,  0.2085023 , -0.03174026,  0.28974476,
        0.25597761,  0.75073056,  1.11993319,  0.26381257,  0.36420746,
        0.60466978, -0.22571613,  0.74309239,  0.31386709, -0.71775144,
        0.303692  ,  0.64046232, -0.77797579, -1.23804229,  1.02668924,
        0.75162623, -0.03628912,  0.28780036,  0.30941909, -0.88

In [491]:
y=df[target]

In [492]:
y=y.to_numpy()

In [493]:
y.shape

(1460, 1)

In [494]:
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]])

In [495]:
y=StandardScaler().fit_transform(y)

In [496]:
y

array([[ 0.34727322],
       [ 0.00728832],
       [ 0.53615372],
       ...,
       [ 1.07761115],
       [-0.48852299],
       [-0.42084081]])

In [497]:
X.shape

(1460, 106)

In [498]:
pca=PCA(n_components=2)

In [499]:
p_components=pca.fit_transform(X)

In [500]:
p_components

array([[ 2.44331074, -1.27881455],
       [ 0.3164582 ,  2.63912728],
       [ 2.85722074, -0.81112073],
       ...,
       [ 1.26182295, -0.85879187],
       [-2.85096818,  3.29515676],
       [-0.77738658,  2.79112998]])

In [501]:
pca.explained_variance_ratio_

array([0.10560233, 0.04472091])

In [502]:
reg=LassoCV()

In [503]:
reg.fit(p_components,y)

/Users/trialaccount/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LassoCV()

In [504]:
reg.coef_

array([0.25387736, 0.01888621])

In [505]:
y = y_1*x_1 + y_2*x_2 

NameError: name 'y_1' is not defined

In [ ]:
y=mx+c

In [ ]:
y=wx+b